### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by alexjfisher** [MiamiOH/puppet-tcpwrappers#3]
Hi.

Do you have plans to make a new release to the forge?

Thanks

**Comment by edestecd** [comment]
Yes, I plan on it, but have been busy lately.  I'll try and get that done
today.

**Comment by alexjfisher** [comment]
Superb! Thank you.

**Comment by edestecd** [comment]
@alexjfisher Released as 1.1.0
https://forge.puppet.com/MiamiOH/tcpwrappers
